version: '3.8'

services:
  # Servicio de la API NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techhelpdesk-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - techhelpdesk-network

networks:
  techhelpdesk-network:
    driver: bridge
