version: '3.8'

services:
  # Servicio de la API NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techhelpdesk-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=aws-0-us-west-2.pooler.supabase.com
      - DB_PORT=6543
      - DB_USERNAME=postgres.eqrueaufobcabmnyodfu
      - DB_PASSWORD=v7jZMZGh6pV6wMhJ
      - DB_DATABASE=postgres
      - DB_SCHEMA=public
      - JWT_SECRET=techhelpdesk_secret_key_2024_kaled_mesa_linus_clan_super_secure
      - JWT_EXPIRATION=24h
    restart: unless-stopped
    networks:
      - techhelpdesk-network

networks:
  techhelpdesk-network:
    driver: bridge
